# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Torsten Mandry
email: torsten@mandry-online.de
description: > # this means to ignore newlines until "baseurl:"
  Als Architekt, Entwickler und Berater unterstütze ich meine Arbeitgeber
  und Kunden seit mehr als 15 Jahren beim Entwurf und der Entwicklung von
  leichtgewichtigen Enterprise-Anwendungen auf Basis von Java und Web-Technologien.
  In diesem Blog halte ich bei Gelegenheit Erkenntnisse aus meinen Projekten fest.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://torstenmandry.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
repository: "torstenmandry/torstenmandry.github.io.git"
twitter_username: torstenmandry
github_username:  torstenmandry

# Build settings
markdown: kramdown
theme: minima
